import org.junit.Test;
import spring_dependency_injection.StringConverter;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'varun' at '18/9/15 10:15 PM' with Gradle 2.4
 *
 * @author varun, @date 18/9/15 10:15 PM
 */
public class StringConverterTest {
    @Test public void testSomeLibraryMethod() {
        StringConverter classUnderTest = new StringConverter();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
