/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'varun' at '9/1/16 3:05 PM' with Gradle 2.9
 *
 * @author varun, @date 9/1/16 3:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String a[]) {
        System.out.println("Hello");
    }
}
